### ISSUE TITLE
Rewrite in C

### ISSUE THREAD

**Issue by devanandersen** [will-r-wang/CMSLearn-Course-Management-System#52]
Hey.

This is really cool. Rails makes me feel weird though. Please rewrite this in C.

Thank you!

**Comment by devanandersen** [comment]
![](https://media2.giphy.com/media/WNn5sTSoCXjpgbjrpO/giphy.gif?cid=ecf05e47lh8v7607kvsaz03ak8b85ha75mo2ny103jb0hokj&rid=giphy.gif&ct=g)

**Comment by will-r-wang** [comment]
😡

**Comment by will-r-wang** [comment]
Closed by: #53

**Comment by devanandersen** [comment]
![](https://media4.giphy.com/media/7SF5scGB2AFrgsXP63/giphy.gif?cid=ecf05e47rgn87b3g4du4xg6l144khfzoj7mg132ak8cvgcp1&rid=giphy.gif&ct=g)
